// src/App.jsx
import { Header} from "./header"
import  Hero  from "./hero"
import  Companies  from "./companies";
import HowItWorks from "./howItWorks";
import Reciepes from "./reciepes";
import Reviews from "./reviews";
import Price from "./price";
import Form from "./form";
import Footer from "./footer";

export default function App(){
  return(
    <>
      <Header/>
      <Hero/>
      <Companies></Companies>
      <HowItWorks></HowItWorks>
      <Reciepes></Reciepes>
      <Reviews></Reviews>
      <Price></Price>
      <Form></Form>
      <Footer></Footer>
    </>
  )
}

// src/App.vue
<script setup lang="ts">
import Header from './components/Header.vue';
import Hero from './components/Hero.vue';
import Companies from './components/Companies.vue';
import HowItWorks from './components/HowItWorks.vue';
import Reciepes from './components/Reciepes.vue';
import Reviews from './components/Reviews.vue';
import Price from './components/Price.vue';
import Form from './components/Form.vue';
import Footer from './components/Footer.vue';
</script>

<template>
  <Header></Header>
  <Hero/>
      <Companies></Companies>
      <HowItWorks></HowItWorks>
      <Reciepes></Reciepes>
      <Reviews></Reviews>
      <Price></Price>
      <Form></Form>
      <Footer></Footer>
</template>

<style scoped>

</style>
